[package]
name = "cargo-wipe"
version = "0.3.1"
edition = "2018"
license = "MIT"
authors = ["Mihai Dinculescu <mihai.dinculescu@iotic-labs.com>"]
description = "recursively wipe target and node_modules folders"
keywords = ["cli", "cargo", "wipe", "target", "node_modules"]
categories = ["command-line-interface", "command-line-utilities"]
readme = "README.md"
repository = "https://github.com/mihai-dinculescu/cargo-wipe"

[dependencies]
anyhow = "1.0.38"
num-format = "0.4.0"
number_prefix = "0.4.0"
structopt = "0.3.21"
yansi = "0.5.0"

[dev-dependencies]
parameterized = "0.3.1"
rand = "0.8.1"
